// Icon mapping for skills - points to SVG files in public/icons
const baseIconPath = '/icons/';

export const iconMap: Record<string, string> = {
    'faJava': `${baseIconPath}java.svg`,
    'faPython': `${baseIconPath}python.svg`,
    'faJs': `${baseIconPath}javascript.svg`,
    'faReact': `${baseIconPath}react.svg`,
    'faHtml5': `${baseIconPath}html5.svg`,
    'faCss3Alt': `${baseIconPath}css.svg`,
    'faVuejs': `${baseIconPath}vuejs.svg`,
    'faSass': `${baseIconPath}sass.svg`,
    'faAndroid': `${baseIconPath}android.svg`,
    'faAppStoreIos': `${baseIconPath}ios.svg`,
    'faNodeJs': `${baseIconPath}nodejs.svg`,
    'faDocker': `${baseIconPath}docker.svg`,
    'faAws': `${baseIconPath}aws.svg`,
    'faGitAlt': `${baseIconPath}git.svg`,
    'faGithub': `${baseIconPath}github.svg`,
    'faGitlab': `${baseIconPath}gitlab.svg`,
    'faLinux': `${baseIconPath}linux.svg`,
    'faFigma': `${baseIconPath}figma.svg`,
    'faSketch': `${baseIconPath}sketch.svg`,
    'faPhp': `${baseIconPath}php.svg`,
    'faCode': `${baseIconPath}nextjs.svg`,
    'faWind': `${baseIconPath}tailwindcss.svg`,
    'faServer': `${baseIconPath}redux.svg`,
    'faTS': `${baseIconPath}typescript.svg`,
    'faRust': `${baseIconPath}rust.svg`,
    'faC': `${baseIconPath}c.svg`,
    'faCpp': `${baseIconPath}cplusplus.svg`,
    'faKotlin': `${baseIconPath}kotlin.svg`,
    'faCSharp': `${baseIconPath}csharp.svg`,
    'faDart': `${baseIconPath}dart.svg`,
    'faSwift': `${baseIconPath}swift.svg`,
    'faCordova': `${baseIconPath}cordova.svg`,
    'faFlutter': `${baseIconPath}flutter.svg`,
    'faJetpackCompose': `${baseIconPath}jetpack-compose.svg`,
    'faKMM': `${baseIconPath}jetpack-compose.svg`,
    'faUnity': `${baseIconPath}unity.svg`,
    'faUnreal': `${baseIconPath}unreal.svg`,
    'faMongo': `${baseIconPath}mongodb.svg`,
    'faPSQL': `${baseIconPath}postgresql.svg`,
    'faMysql': `${baseIconPath}mysql.svg`,
    'faNeo': `${baseIconPath}neo4j.svg`,
    'faRealm': `${baseIconPath}realm.svg`,
    'faCDB': `${baseIconPath}cockroachdb.svg`,
    'faVercel': `${baseIconPath}vercel.svg`,
    'faNetlify': `${baseIconPath}netlify.svg`,
    'faXML': `${baseIconPath}xml.svg`,
    'faJSON': `${baseIconPath}json.svg`,
    'faMaterial': `${baseIconPath}materialdesign.svg`,
    'faProjectDiagram': `${baseIconPath}project-diagram.svg`,
    'faCodeBranch': `${baseIconPath}code-branch.svg`,
    'faCloud': `${baseIconPath}cloud.svg`,
    'faDharmachakra': `${baseIconPath}kubernetes.svg`,
    'faCog': `${baseIconPath}cog.svg`,
    'faPaintBrush': `${baseIconPath}paintbrush.svg`,
    'faImage': `${baseIconPath}image.svg`,
    'faDrawPolygon': `${baseIconPath}draw-polygon.svg`,
    'faCube': `${baseIconPath}cube.svg`,
    'faUsers': `${baseIconPath}users.svg`,
    'faMobileAlt': `${baseIconPath}mobile.svg`,
};

export const DEFAULT_ICON = `${baseIconPath}code.svg`;
